In [2]:
import numpy as np

In [39]:
a = np.zeros((60000, 60000), dtype=np.float16)
print(a.size * a.itemsize)

7200000000


In [26]:
a = np.zeros((28, 28)).flatten()
b = (np.ones((28, 28)) * 255).flatten()

In [28]:
from scipy.spatial.distance import euclidean
print(euclidean(a, b))

7140.0


In [40]:
# Max size of float and ints
print(np.finfo(np.float16).max)
print(np.iinfo(np.uint8).max)

65500.0
255


In [143]:
import DistMatrix
dm = DistMatrix.load_dist_matrix(10)
dm = dm[:4, :4]
print(dm)

[[   0. 2388. 2774. 2554.]
 [2388.    0. 2898. 2766.]
 [2774. 2898.    0. 2572.]
 [2554. 2766. 2572.    0.]]


In [147]:
import Graph
import importlib
importlib.reload(Graph)
G = Graph.construct_knn_graph(dm, k=1)
print(dm)
print("#\n#\n", G.toarray())

100%|██████████| 4/4 [00:00<00:00, 8008.22it/s]

[[   0. 2388. 2774. 2554.]
 [2388.    0. 2898. 2766.]
 [2774. 2898.    0. 2572.]
 [2554. 2766. 2572.    0.]]
#
#
 [[0 1 0 1]
 [1 0 0 0]
 [0 0 0 1]
 [1 0 1 0]]


In [60]:
a = np.array([1,1,1])
print(a)
print(a[:3])

[1 1 1]
[1 1 1]
