In [3]:
from sklearn import datasets

In [2]:
import importlib
import sys
sys.path.append(r"F:\Git\Bachelor2.1\GSSL\Construction")
import GraphConstructor
import numpy as np
import pymde

In [4]:
importlib.reload(GraphConstructor)

<module 'GraphConstructor' from 'F:\\Git\\Bachelor2.1\\GSSL\\Construction\\GraphConstructor.py'>

In [7]:
mnist = pymde.datasets.MNIST()

Jul 03 02:50:06 PM: Loading cached dataset.


In [29]:
g_constructor = GraphConstructor.GraphConstructor()
g_constructor.create_weight_matrix()

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]
